set_property IOSTANDARD LVCMOS25 [get_ports clock_p]
set_property IOSTANDARD LVCMOS25 [get_ports reset_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[0]}]

set_property PACKAGE_PIN P15 [get_ports clock_p]
set_property PACKAGE_PIN U9 [get_ports reset_n]
set_property PACKAGE_PIN K15 [get_ports {hdmi_clk[1]}]
set_property PACKAGE_PIN G18 [get_ports {hdmi_d0[1]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_d1[1]}]
set_property PACKAGE_PIN J14 [get_ports {hdmi_d2[1]}]
