# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/baktiiar/workspace/github/CSI2Rx/project/IPcore/ddr3_if/ddr3_if.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ddr3_if || ORIG_REF_NAME==ddr3_if}]
