set_property PACKAGE_PIN N5 [get_ports {csi0_clk[1]}]
set_property PACKAGE_PIN M6 [get_ports {csi0_d0[1]}]
set_property PACKAGE_PIN L6 [get_ports {csi0_d1[1]}]
set_property PACKAGE_PIN P4 [get_ports {csi0_d2[1]}]
set_property PACKAGE_PIN M4 [get_ports {csi0_d3[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_clk[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_clk[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d0[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d0[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d1[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d1[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d2[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d2[0]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d3[1]}]
set_property IOSTANDARD LVDS_25 [get_ports {csi0_d3[0]}]
set_property PACKAGE_PIN V9 [get_ports cam_i2c_sda]
set_property PACKAGE_PIN V7 [get_ports cam_i2c_sck]
set_property PACKAGE_PIN V6 [get_ports cam_rstn]
set_property PACKAGE_PIN P15 [get_ports clock_p]

set_property IOSTANDARD LVCMOS25 [get_ports cam_i2c_sck]
set_property IOSTANDARD LVCMOS25 [get_ports cam_i2c_sda]
set_property IOSTANDARD LVCMOS25 [get_ports cam_mclk]
set_property IOSTANDARD LVCMOS25 [get_ports cam_rstn]
set_property IOSTANDARD LVCMOS25 [get_ports clock_p]
set_property IOSTANDARD LVCMOS25 [get_ports reset_n]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_clk[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d0[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d1[0]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[1]}]
set_property IOSTANDARD TMDS_33 [get_ports {hdmi_d2[0]}]

set_property PACKAGE_PIN L3 [get_ports cam_mclk]
set_property PACKAGE_PIN K15 [get_ports {hdmi_clk[1]}]
set_property PACKAGE_PIN G18 [get_ports {hdmi_d0[1]}]
set_property PACKAGE_PIN H17 [get_ports {hdmi_d1[1]}]
set_property PACKAGE_PIN J14 [get_ports {hdmi_d2[1]}]
set_property PACKAGE_PIN U9 [get_ports reset_n]

set_property PULLUP true [get_ports reset_n]



connect_debug_port u_ila_0/probe0 [get_nets [list cam_ctl/i2c_if/sck_int]]

create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 4 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER true [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 4096 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list sys_clock]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list cam_i2c_sda_TRI]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 1 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list cam_i2c_sck_TRI]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 1 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list cam_ctl/i2c_if/sda_int]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 1 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list cam_ctl/i2c_if/i2c_sda_reg0]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 1 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list cam_ctl/i2c_if/i2c_sck_reg0]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets sys_clock]
