# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk.xci
# IP: The module: 'system_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk.xci
# IP: The module: 'system_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: /home/alga/workspace/github/CSI2Rx/project/IPcore/system_clk/system_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
