# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a100tcsg324-2

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.cache/wt [current_project]
set_property parent.project_path /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/dvi-tx/dvi_tx_tmds_enc.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/dvi-tx/dvi_tx_tmds_phy.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/dvi-tx/dvi_tx_clk_drv.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/dvi-tx/dvi_tx_top.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/video-misc/video_timing_ctrl.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/video-misc/test_pattern_gen.vhd
  /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.srcs/sources_1/new/VHDL_test.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.srcs/constrs_1/new/test.xdc
set_property used_in_implementation false [get_files /home/alga/workspace/github/CSI2Rx/project/HDMI_test/HDMI_test.srcs/constrs_1/new/test.xdc]


synth_design -top VHDL_test -part xc7a100tcsg324-2


write_checkpoint -force -noxdef VHDL_test.dcp

catch { report_utilization -file VHDL_test_utilization_synth.rpt -pb VHDL_test_utilization_synth.pb }
