# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/baktiiar/workspace/github/CSI2Rx/project/IPcore/input_line_buffer_1/input_line_buffer.xci
# IP: The module: 'input_line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/baktiiar/workspace/github/CSI2Rx/project/IPcore/input_line_buffer_1/input_line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_line_buffer'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# IP: /home/baktiiar/workspace/github/CSI2Rx/project/IPcore/input_line_buffer_1/input_line_buffer.xci
# IP: The module: 'input_line_buffer' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/baktiiar/workspace/github/CSI2Rx/project/IPcore/input_line_buffer_1/input_line_buffer_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'input_line_buffer'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
